### ISSUE TITLE
Wrapping in div

### ISSUE THREAD

**Issue by jupitercow** [GregoryPotdevin/react-hogan#1]
I am pretty interested in this as a way to gain fallback and server rendering, but keeps wrapping everything I make in `div` tags. Which makes for a difference in my php rendering and just... screws up layout. Is this by design? Is there a way to keep it from happening?

Thanks for sharing.

**Comment by jupitercow** [comment]
Example.

My mustache template:

```
<footer className={{styles.footer}}>
  <section>
    <p>{{license}}</p>
  </section>
  <section>
    <p>{{about}}</p>
  </section>
</footer>
```

React:

```
return (
    <Hogan template={template} data={{
        styles: styles,
        license: license,
        about: about
    }} />
);
```

Renders to:

```
<div>
  <footer classname="footer__app-components-Footer-styles__12LGe">
      <section>
        <p>This project is licensed under the MIT license.</p>
      </section>
      <section>
        <p>Made with love by [object Object].</p>
      </section>
    </footer>
</div>
```

Using Hogan:
<img width="359" alt="screen shot 2016-05-25 at 10 48 43 am" src="https://cloud.githubusercontent.com/assets/1641472/15546649/4fcc8b6a-2266-11e6-99b4-85eedd3b5f13.png">

The original react component:

```
  return (
    <footer className={styles.footer}>
      <section>
        <p>This project is licensed under the MIT license.</p>
      </section>
      <section>
        <p>Made with love by <a href="https://twitter.com/mxstbr">Max Stoiber</a>.</p>
      </section>
    </footer>
  );
```

Renders to:

```
<footer class="footer__app-components-Footer-styles__12LGe"><section><p>This project is licensed under the MIT license.</p></section><section><p><!-- react-text: 35 -->Made with love by <!-- /react-text --><a href="https://twitter.com/mxstbr">Max Stoiber</a><!-- react-text: 37 -->.<!-- /react-text --></p></section></footer>
```

Original:
<img width="794" alt="screen shot 2016-05-25 at 10 46 07 am" src="https://cloud.githubusercontent.com/assets/1641472/15546654/531313e8-2266-11e6-9ce0-bfb8fd632028.png">

**Comment by jupitercow** [comment]
If found the component param, and, after some thought, I get it. You need to render a component, and place the template html inside of it. This makes sense. I will either figure out how to design around it... or it just won't work for me. This is a REALLY handy tool though. Thanks again for sharing!

**Comment by GregoryPotdevin** [comment]
Didn't get a chance to answer, but that is the problem, yes. 

One workaround in your case would be to use "footer" as the outer tag and put the contents of your footer as a template. Would that work for you ?

**Comment by jupitercow** [comment]
The problem for me, is how I connect everything to my server side setup. I am running through strategies for creating a marketing site that _has_ to have fallback. I want a solid way to have one set of templates. Previously, I was going to use Backbone for this, but I would love to stop using Backbone, and focus future dev on React. So I am just trying to convince myself that will be a safe bet. I don't really want to create wrappers in php (on the server)... so still deciding what to do. I think this is a pretty great option though. Thanks again.
